name: Test

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2

    - name: Configure Liquibase image with changelog file
      run: |
        printf 'FROM liquibase/liquibase\nENV LIQUIBASE_COMMAND_CHANGELOG_FILE=task.sql\n' | docker build -t liquibase/liquibase -

    - name: Run the bash tests
      run: |
        ./test.sh
